#!/bin/sh

export tracer_file="$PWD/trace"

tracer_script='#!/bin/sh

is_compile_command() {
    for a; do
        [ "$a" = "-c" ] && return 0
    done
    return 1
}

cmd=${0##*/}
if is_compile_command "$@"; then
    echo "$cmd $*" >>"$tracer_file"
fi

PATH=${PATH#*:} exec $cmd "$@"
'

if ! [ -d ".tracer" ]; then
    mkdir .tracer && cd .tracer
    printf "${tracer_script}" >tracer
    chmod +x tracer
    ln -s tracer ${CROSS_COMPILE}gcc
    ln -s tracer ${CROSS_COMPILE}g++
    cd ..
fi

cat /dev/null >"${tracer_file}"

PATH="$PWD/.tracer:$PATH" make $@
